In [54]:
import pandas as pd
import numpy as np

chiens = pd.DataFrame({
    "nom": ["Rex", "Luna", "Biscuit", "Nougat", "Pixel", "Olive", "Caramel", "Fifi"],
    "race": ["labrador", "jack russell", "bichon", "beagle", "jack russell", "bichon", "labrador", "bichon"],
    "age_annees": [3, 7, 12, 5, 2, 9, 6, 11],
    "poids_kg": [29.5, 6.2, 4.1, np.nan, 5.8, 4.5, 31.0, 3.9],
    "proprio_id": [101, 102, 103, 104, 105, 101, 106, 107]
})

proprios = pd.DataFrame({
    "id": [101, 102, 103, 104, 105, 106, 107],
    "ville": ["Bruxelles", "Liège", "Forest", "Namur", "Bruxelles", "Gand", "Uccle"]
})

1. Affiche les 3 premières lignes et les dimensions du DataFrame.

In [10]:
chiens.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nom         8 non-null      str
 1   race        8 non-null      str
 2   age_annees  8 non-null      int64
 3   poids_kg    7 non-null      float64
 4   proprio_id  8 non-null      int64
dtypes: float64(1), int64(2), str(2)
memory usage: 557.0 bytes

In [2]:
display(chiens.head(3))
display(chiens.shape)
display(proprios.head(3))
display(proprios.shape)

       nom          race  age_annees  poids_kg  proprio_id
0      Rex      labrador           3      29.5         101
1     Luna  jack russell           7       6.2         102
2  Biscuit        bichon          12       4.1         103

(8, 5)

    id      ville
0  101  Bruxelles
1  102      Liège
2  103     Forest

(7, 2)

2. Affiche le nom et l'âge du chien en position 4 (par position, pas par label).

In [30]:
display(chiens.iloc[4])
display(chiens[['nom','age_annees']].iloc[[4]])

nom                  Pixel
race          jack russell
age_annees               2
poids_kg               5.8
proprio_id             105
age_humain              14
Name: 4, dtype: object

     nom  age_annees
4  Pixel           2

3. Affiche tous les chiens de plus de 5 kg.

In [32]:
display(chiens.loc[chiens['poids_kg']>5])

       nom          race  age_annees  poids_kg  proprio_id
0      Rex      labrador           3      29.5         101
1     Luna  jack russell           7       6.2         102
4    Pixel  jack russell           2       5.8         105
6  Caramel      labrador           6      31.0         106

4. Affiche les jack russell de moins de 8 ans.

In [ ]:
display(chiens.loc[(chiens['race']=='jack russell')&(chiens['age_annees']<8)])

     nom          race  age_annees  poids_kg  proprio_id
1   Luna  jack russell           7       6.2         102
4  Pixel  jack russell           2       5.8         105

5. Crée une colonne age_humain (âge × 7).

In [28]:
chiens['age_humain']=chiens['age_annees']*7
display(chiens)

       nom          race  age_annees   poids_kg  proprio_id  age_humain
0      Rex      labrador           3  29.500000         101          21
1     Luna  jack russell           7   6.200000         102          49
2  Biscuit        bichon          12   4.100000         103          84
3   Nougat        beagle           5  12.142857         104          35
4    Pixel  jack russell           2   5.800000         105          14
5    Olive        bichon           9   4.500000         101          63
6  Caramel      labrador           6  31.000000         106          42
7     Fifi        bichon          11   3.900000         107          77

6. Quels sont les 3 chiens les plus lourds ?

In [34]:
display(chiens.sort_values('poids_kg',ascending=False).head(3))

       nom          race  age_annees  poids_kg  proprio_id
6  Caramel      labrador           6      31.0         106
0      Rex      labrador           3      29.5         101
1     Luna  jack russell           7       6.2         102

7. Combien y a-t-il de chiens par race ?

In [37]:
display(chiens['race'].value_counts())

race
bichon          3
labrador        2
jack russell    2
beagle          1
Name: count, dtype: int64

8. Quel est le poids moyen par race ?

In [48]:
display(chiens.groupby('race')['poids_kg'].mean())

race
beagle                NaN
bichon           4.166667
jack russell     6.000000
labrador        30.250000
Name: poids_kg, dtype: float64

9. En une seule opération : poids moyen ET âge maximum par race, avec des colonnes proprement nommées.

In [49]:
display(chiens.groupby('race').agg(poids_moyen=('poids_kg','mean'),age_max=('age_annees','max')))

              poids_moyen  age_max
race
beagle                NaN        5
bichon           4.166667       12
jack russell     6.000000        7
labrador        30.250000        6

10. Un poids manque dans les données. Trouve-le, puis remplace-le par le poids moyen.

In [55]:
display(chiens[chiens['poids_kg'].isna()])
chiens['poids_kg']=chiens['poids_kg'].fillna(chiens['poids_kg'].mean())
display(chiens)

      nom    race  age_annees  poids_kg  proprio_id
3  Nougat  beagle           5       NaN         104

       nom          race  age_annees   poids_kg  proprio_id
0      Rex      labrador           3  29.500000         101
1     Luna  jack russell           7   6.200000         102
2  Biscuit        bichon          12   4.100000         103
3   Nougat        beagle           5  12.142857         104
4    Pixel  jack russell           2   5.800000         105
5    Olive        bichon           9   4.500000         101
6  Caramel      labrador           6  31.000000         106
7     Fifi        bichon          11   3.900000         107

11. Affiche chaque chien avec la ville de son propriétaire (chiens.proprio_id ↔ proprios.id, noms différents).

In [56]:
display(chiens.merge(proprios, left_on="proprio_id", right_on="id", how="left"))

       nom          race  age_annees   poids_kg  proprio_id   id      ville
0      Rex      labrador           3  29.500000         101  101  Bruxelles
1     Luna  jack russell           7   6.200000         102  102      Liège
2  Biscuit        bichon          12   4.100000         103  103     Forest
3   Nougat        beagle           5  12.142857         104  104      Namur
4    Pixel  jack russell           2   5.800000         105  105  Bruxelles
5    Olive        bichon           9   4.500000         101  101  Bruxelles
6  Caramel      labrador           6  31.000000         106  106       Gand
7     Fifi        bichon          11   3.900000         107  107      Uccle

12. Dans quelle ville vit le chien le plus âgé ? Une seule chaîne d'opérations.

In [63]:
display(chiens.sort_values("age_annees", ascending=False).head(1).merge(proprios, left_on="proprio_id", right_on="id", how="left"))

       nom    race  age_annees  poids_kg  proprio_id   id   ville
0  Biscuit  bichon          12       4.1         103  103  Forest

Autre option plus solide (merger d'abord comme ça tout le monde à sa ville puis isoler le top 1 âge puis demander d'afficher la ville seulement)

In [64]:
display(chiens.merge(proprios, left_on="proprio_id", right_on="id", how="left").sort_values("age_annees", ascending=False).head(1)["ville"])

2    Forest
Name: ville, dtype: str